bot:
  server: "irc.rrerr.net"
  port: 6667

  nickname: "botter"
  realname: "Botter IRC Bot"

  channels:
    - "#lobby"
    - "#test"
  
  modules:
    enabled:
      - ctcp
      - ddg
      - google
      - youtube
    config:
      ctcp:
        version: true    # Reply to CTCP VERSION
      ddg:
        command: "!d"
        searching_for_str: "Searching \x034DuckDuckGo\x0f for: %arg"
        no_results_str: "Nothing was found :("
      google:
        command: "!g"
        searching_for_str: "Searching \x0312G\x034o\x038o\x0312g\x039l\x034e\x0f for: %arg"
      youtube:
        banner: "[\x02You\x034Tube\x0f]"
        enable_not_found_message: false    # Enable "Video not found" message (which can get quite spammy)
        not_found_str: "Video not found ;_;"
  